// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARxpbNax-fyolHBcdm2QaHcKisCit5A1o',
    appId: '1:783853189482:web:83bebc168f757c55ca4d13',
    messagingSenderId: '783853189482',
    projectId: 'proj-todo-sat',
    authDomain: 'proj-todo-sat.firebaseapp.com',
    storageBucket: 'proj-todo-sat.appspot.com',
    measurementId: 'G-49RT8QV95N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0rYbViyw3lA6KLkH0EEXqfTmbzdrkCRw',
    appId: '1:783853189482:android:ed291d8291eab70bca4d13',
    messagingSenderId: '783853189482',
    projectId: 'proj-todo-sat',
    storageBucket: 'proj-todo-sat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJZw00II8rP-nAveMKa7cPH-OIH-tpthk',
    appId: '1:783853189482:ios:204b77e14d77d759ca4d13',
    messagingSenderId: '783853189482',
    projectId: 'proj-todo-sat',
    storageBucket: 'proj-todo-sat.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJZw00II8rP-nAveMKa7cPH-OIH-tpthk',
    appId: '1:783853189482:ios:3f2ce77eb2f7127bca4d13',
    messagingSenderId: '783853189482',
    projectId: 'proj-todo-sat',
    storageBucket: 'proj-todo-sat.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
